---
title: "Risques HUS"
author: "JCB"
date: "Friday, July 04, 2014"
output: html_document
---

Risques HUS
===========

Sources:

- kayser permanente (grille)
- SDACR du Var (définitions)
- risque sismique: base de données de l'université de Strasbourg [RENASS](http://renass.unistra.fr/recherche). Possibilité de télécharger les données au format TSV (tab separated virgule)
- site de la DREAL installations classées [DREAL](http://www.installationsclassees.developpement-durable.gouv.fr/rechercheICForm.php)
- Plan de prévention des risques technologiques [PPRT](http://www.alsace.developpement-durable.gouv.fr/les-plans-de-prevention-des-r266.html). La doc technique se trouve dans le dossier **HUS Evaluation Risques/doc technique DREAL**
- carte des installation Seveso en Alsace [SEVESO](http://www.alsace.developpement-durable.gouv.fr/cartes-des-installations-seveso-a798.html)
- liste des établissements classés sur la CUS: fichier Libre Office dans dossier perso.

Strasbourg regroupe dans sa communauté urbaine près de la moitié de la population du Bas-Rhin (600.000 personnes) et la quasi-totalité des industries à risques (Sévéso suil haut). La ville appartient à la région du Rhin Supérieure, entité géopolitique comptant plus de 6 millions d'habitants (1% de la population européenne), regroupant l'Alsace, le Bade-Wurtemberg et les régions de Suisse du nord (Bâle, Aargau). C'est une région riche, en croissance démographique soutenue, siège des institutions européennes et d'un tissus industriel dense. Si le dynamisme démographique est lié à un taux de natalité important dans la partie française, c'est le solde migratoire qui prédomine dans les parties allemandes et Suisse.
La présence des institutions européennes et d'une représentation diplomatique dense en font une cible privilégiée pour les revendications plus ou moins musclées de contestataires et pour des actions terroristes. Strasbourg est probablement la ville de France - en dehors de Paris- qui connait le plus de voyages officiels dont la couverture médicale est assurée par les HUS.

Le CHU à la fois CH du secteur sanitaire 2 et ESR assume une responsabilité complexe liée à ses double mission d'hôpital de proximité et de recours pour l'ensemble de sa région voire au delà.

Habituellement les risques sont divisés endeux grandes catégories: les risques internes à l'établissement et les risques extérieurs à celui-ci. Sele la seconde catégorie sera abordée dans ce document.

Fichier
-------

- NB: LES NOMS DE FICHIERS AVEC ACCENTS PASSENT MAL DANS GITHUB.
- __Etablissements classés 67.csv__ source: site de la DREAL. Entreprises classées du Bas-Rhin. Récupération fastidieuse car la base de donnée ne délivre que 20 lignes à la fois. Il me semble que dans RBloggers il y a un blog qui traite de ce problème. Date de saisie: 5 juin 2014. Il me semble que les mêmes entreprises apparaissent plusieurs fois ? Le fichier source est enregistré au format CSV avec l'option "Metttre entre uillemets toutes les cellules" et la virgule comme séparateur de champ.

- __Etablissements classes sur la CUS.csv__ même source. En fait le fichier ne contient que les entreprises de Strasbourg (et non de la CUS).

_ __Seismes recents en Alsace.csv__ et __seisme.tsv__ Fichier récupéré sur le site du RENASS avec les modalités de recherche suivantes:

  - date de début: 2013-06-09
  - date de fin: 2014-06-09
  -  Magnitude minimale
  - Magnitude maximale: 
  - Latitude minimale: 49.03333
  - Latitude maximale: 47.5
  - Longitude minimale: 6.95
  - Longitude maximale: 8.166667
  -Profondeur minimale
  -Profondeur maximale (Les profondeurs sont exprimés en km.)
Divers
Limite
Offset
Trier par: dates croissantes
ID de l'évenement (Toutes les autres valeurs seront ignorées en cas d'utilisation d'un ID.)
Rayon
Latitude
Longitude
Rayon (exprimé en degré, 1° = 111 km)


Le fichier récupéré est du type TSV (Tab separated value), avec les intitulés de colonnes suivants:
```
    Identifiant du séisme
    Heure UTC
    Latitude
    Longitude
    Magnitude
    Type de magnitude
    Profondeur (en km)
    Type de profondeur
    Catalogue
    Mode d'évaluation
    Nombre de stations utilisées
    Nombre de phases
    Gap azimuthal
    Mode d'évaluation
    Ville significative
    Distance de la ville (en km)
```

Risques locaux
==============

Un __risque__ est un évènement inattendu (mais prévisible) indésirable en raison de ses conséquences humaines et/ou financières résultant de la conjonction d'un __alea__ non maîtrisé ou non maçitrisable et d'une __vulnérabilité__.

Deux caractéristiques: la __gravité__ et la _fréquence__. Les risques majeurs sont caractérisés par une gravité majeure et une fréquence rare voire exeptionnelle.

La fréquence est mesurée par l'analyse des évènements passés. La probabilité de survenue ets le plus souvent rétrospective.

Rassemblement de foule
----------------------

    - Zenith (PMC, Stade de la Meinau)
    - Marché de Noël (un attentat déjoué en décembre 2000). Grande proximité du site et de l'hôpital civil.
    - parc d'attraction de Rust.
    
Institutions européennes
------------------------

    - représentations nationales (Kurdes: grèves de la faim, immolation de masse)
    - parlement européen (VO, alertes poudre)
    - cour européenne des droits de l'homme
    - siège de Europol
    
Bateaux de croisière
--------------------

    - TIA norovirus
    - collision
    - risque de crues et d'innondation
    
Nucléaire
----------

    - Cronenbourg (laboratoire du CNRS)
    - Fessenheim
    - Philipsburg
    
Chimiques
---------

    - faculté de chimie (tour)
    - Usines SEVESO. Une dizaine d'usines dans le 67
        - port du rhin (Strasbourg)
        - Lanxess (Wantzenau - CUS)
        - Rohm & Haas (Lauterbourg)
        - Dow (Herlisheim)
    - Transport de matières dangereuses (TMD)
        - Triage d'Hausbergen
        - Gazoduc de Strasbourg (Gaz de Strasbourg, Gaz de France-Haute pression)
        - Pipelines sur la CUS: PL Trapil ODC3, Compagnie Rénane de Raffinage (CRR), Raffinerie de Strasbourg (RS) et Groupement pétrolier de Strasboug (GPS). Transport d'hydrocarbures

Transports
-----------

    - Tunnel TRAM (tunnel Maurice Lemaire, Schirmeck, Bitche). Collision bus/Tram [17/10/2009](http://www.lefigaro.fr/flash-actu/2009/10/17/01011-20091017FILWWW00599-collision-tram-bus-a-strasbourg.php)
    - TGV (tunnel de Saverne)
    - TDM, Castor
    - Pipelines trans-européens (gaz, pétrole)
    - Aéroports (Entzheim, Bâle)

Biologique
----------
    - Labo P3


Risques environnementaux (Naturels)
------------------------

    - Sismique: une centaine de secousses sont observées tous les ans dans la région du rhin supérieur. Ce sont essentiellement des des seismes peu profonds, destructeurs à partir d'une échelle de 5 sur l'échelle de Richter.
Toute la CUS est classée en zone Ib (sismicité faible mais règles parasismiques opposables). Bâle 18 octobre 1356, 300 morts.

    - cavités en sous-sol (Schiltigheim 1994): il existe sur la CUS un réseau importrant de caves et de galeries liées au stockage des brasseries, notamment dans les secteurs Nord et Ouest de la CUS. Les localisations font l'objet d'un recensement par la CUS et le BRGM (en 2001 268 sites avaient été répertoriés dont 133 caves-abris, 38 ouvrages militaires et 36 réseaux de galeries).
    - fragilité du réseau d'eau potable
    - Innondation: secteur Bruche (HTP) et Ill (NHC) [Plan de prévention es risques innondation](http://www.bas-rhin.gouv.fr/pprnt/fichiers/arrete_portant_prescription_du_ppri_de_la_cus.pdf). Risques pris en compte: remontée de nappe et submersion.
[Plan de prévention des risques naturels (PPR)](http://catalogue.prim.net/143_plans-de-prevention-des-risques-naturels-ppr-risques-d-inondation-guide-methodologique.html).

Risques d'innondation dans la [CUS](http://www.strasbourg.eu/vie-quotidienne/prevention-securite/risques-majeurs/risque-inondation-cus)

    - feux de forêts
    - coulées de boue
    - mouvements de terrain
    - tornades: accident catastrophique du parc Pourtales (juillet 2001, 13 morts, une centaine de blessés)
    - Plan intempérie zone est (PZM): plusieurs centaines d'automobilistes bloqués par la neige sur l'autoroute A4.
    - Températures extrêmes: plan canicule, plan grand froid. Hôpital de HTP privé de chauffage suite explosion de la centrale thermique de Hautepierre [1988](http://www.hautepierre-energie.fr/nous_connaitre/historique/).
    
Autres
------

    - fusillades (risque faible, impact élevé)
    - afflux massif de brûlés
    - vulnérabilité vis à vis des fournisseurs: oxygène
    - vulnérabilité pour l'alimentation en eau: pas de réserves

ToDo
====
- contacter Yves François

http://www.nhlbi.nih.gov/guidelines/obesity/bmi_tbl.pdf

 A la mi-décembre 2000, la coopération entre DST et police allemande aboutit à l'arrestation de quatre individus d'origine algérienne. Ces derniers, basés à Francfort, visaient le marché de Noël de Strasbourg, événement populaire drainant des centaines de milliers de visiteurs chaque année. Leurs cibles : le marché en lui-même, mais aussi la cathédrale Notre-Dame voire, selon certaines sources, le siège du Parlement européen. C'est le transport d'armes et de munition qui aura trahi ceux qu'on présente désormais comme de simples exécutants. Lors de leur intervention, les autorités saisiront cependant un véritable arsenal et de nombreux faux papiers. Il faudra attendre six mois pour retrouver le cerveau de l'opération : Mohammed Bensakhria, un leader du Groupe salafiste pour la prédication et le combat, sera arrêté au printemps 2001 en Espagne. Extradé en France, il a depuis écopé d'une peine de 10 ans de prison.
[source](http://www.linternaute.com/actualite/faits-divers/attentats-rates/marche-de-strasbourg.shtml)

[SEVESO](http://fr.wikipedia.org/wiki/Seveso) Seveso est une commune italienne d'environ 22 200 habitants située dans la province de Monza et de la Brianza, dans la région de Lombardie, dans le nord-ouest de l'Italie. Son nom vient de celui de la rivière éponyme qui traverse la commune dans le sens nord-sud.

Elle est surtout connue depuis la catastrophe de Seveso, catastrophe industrielle survenue le 10 juillet 1976 et qui vit un nuage de dioxine se répandre dans les environs après l'explosion de l'usine chimique Icmesa située dans la ville voisine de Meda.

Elle est attachée depuis à la directive [européenne 96/82/CE](http://fr.wikipedia.org/wiki/Directive_Seveso) qui impose notamment le recensement des établissements industriels présentant des risques importants. Les établissements sont classés « Seveso » en fonction des quantités et des types de produits dangereux qu'ils accueillent. Il existe ainsi deux seuils différents classant les établissements en « Seveso seuil bas » ou en « Seveso seuil haut ». Les établissements militaires et les dangers liés aux rayonnements ionisants (nucléaires) ne sont pas concernés par cette directive.

Le calcul de dépassement de seuil se réalise par une somme pondérée des masses de produits présents dans l'établissement.

    Les établissements dont le premier seuil n'est pas franchi ne sont pas concernées par la directive
    Les établissements qui dépassent le premier seuil sont concernées par la Directive et sont classées « Seveso seuil bas ».
    
    Les établissements qui dépassent le second seuil sont elles classées « Seveso seuil haut » (autre dénomination équivalente : « Seveso AS », forme abrégée de « Seveso soumise à Autorisation Servitude d'utilité publique »).

